meta_title: "Alfred takes notes - Assistant personnel"
meta_description: "Organiser sa progression et ses notes professionnelles et outils de travail pour développeur(se) web."
meta_image: "cover.png" # should exist in `app/assets/images/`
